# Generated by Django 4.0.1 on 2022-02-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_uz',
            new_name='name',
        ),
    ]
